export const SET_AUTH_LOADING = "AUTH_LOADING",
  SET_AUTH_ERROR = "AUTH_ERROR",
  LOGIN = "LOGIN",
  LOG_OUT = "LOG_OUT";

export const SET_QA_LOADING = "SET_QUESTIONS_LOADING",
  SET_QA_ERROR = "SET_QUESTION_ERROR",
  SET_QUESTIONS = "SET_QUESTIONS",
  SET_ANSWERS = "SET_ANSWERS";

export const SET_FILTER = "SET_FILTER";
